# Custom commands
  autowire:
    commands:
      forced:
        _site_checkout:
          class: \VM\Console\Command\Develop\SiteCheckoutCommand
        _site_compose:
          class: \VM\Console\Command\Develop\SiteComposeCommand
        _site_settings_db:
          class: \VM\Console\Command\Develop\SiteSettingsDbCommand
        _site_settings_memcache:
          class: \VM\Console\Command\Develop\SiteSettingsMemcacheCommand
        _site_db_import:
          class: \VM\Console\Command\Develop\SiteDbImportCommand
      name: { }
    chain:
      name:
        'site:new':
          file: '~/.config/composer/dev_scripts/vendor/dennisdigital/drupal_console_commands/config/chain/chain-site-new.yml'
        'site:build':
          file: '~/.config/composer/dev_scripts/vendor/dennisdigital/drupal_console_commands/config/chain/chain-site-build.yml'
        'site:install':
          file: '~/.config/composer/dev_scripts/vendor/dennisdigital/drupal_console_commands/config/chain/chain-site-install.yml'
      disabled:
        'site:test':
          file: '~/.composer/dev_scripts/vendor/dennisdigital/drupal_console_commands/config/chain/chain-site-test.yml'
