# Custom commands
  autowire:
    commands:
      forced: {  }
      name:
        'site:checkout':
          class: \VM\Console\Command\Develop\SiteCheckoutCommand
        'site:compose':
          class: \VM\Console\Command\Develop\SiteComposeCommand
        'site:settings:db':
          class: \VM\Console\Command\Develop\SiteSettingsDbCommand
        'site:build':
          class: \VM\Console\Command\Develop\SiteBuildCommand
        'site:db:import':
          class: \VM\Console\Command\Develop\SiteDbImportCommand

