application:
  autowire:
    commands:
      forced:
        "site:build":
          class: \DennisDigital\Drupal\Console\Command\SiteBuildCommand
        'site:checkout':
          class: \DennisDigital\Drupal\Console\Command\SiteCheckoutCommand
        'site:compose':
          class: \DennisDigital\Drupal\Console\Command\SiteComposeCommand
        'site:settings:db':
          class: \DennisDigital\Drupal\Console\Command\SiteSettingsDbCommand
        'site:settings:memcache':
          class: \DennisDigital\Drupal\Console\Command\SiteSettingsMemcacheCommand
        'site:settings:local':
          class: \DennisDigital\Drupal\Console\Command\SiteSettingsLocalCommand
        'site:drush:alias':
          class: \DennisDigital\Drupal\Console\Command\SiteDrushAliasCommand
        'site:db:import':
          class: \DennisDigital\Drupal\Console\Command\SiteDbImportCommand
        'site:behat:setup':
          class: \DennisDigital\Drupal\Console\Command\SiteBehatSetupCommand
        'site:phpunit:setup':
          class: \DennisDigital\Drupal\Console\Command\SitePHPUnitSetupCommand
        'site:npm':
          class: \DennisDigital\Drupal\Console\Command\SiteNPMCommand
        'site:grunt':
          class: \DennisDigital\Drupal\Console\Command\SiteGruntCommand
        'site:test:exec':
          class: \DennisDigital\Drupal\Console\Command\SiteTestExecCommand
        'site:update':
          class: \DennisDigital\Drupal\Console\Command\SiteUpdateCommand
      name: { }
