# Usage: drupal site:configure --placeholder="name:subscriptions"
command:
  name: site:configure
  description: 'Generates the necessary configuration files.'
commands:
# Create settings.db.php
  - command: site:settings:db
    arguments:
      name: '%{{name}}'
# Create settings.local.php
  - command: site:settings:local
    arguments:
      name: '%{{name}}'
# Create settings.memcache.php
  - command: site:settings:memcache
    arguments:
      name: '%{{name}}'
# Create the drush alias
  - command: site:drush:alias
    arguments:
      name: '%{{name}}'
