commands:
# Build from template
  - command: exec
    arguments:
      bin: 'composer create-project %{{project|dennisdigital/drupal-project:8.x-dev}} %{{directory|/vagrant/repos/new-site}} %{{version|8.x-dev}} --stability dev --no-interaction'
