commands:
# Example of a chain calling another chain with placeholders
  - command: exec
    arguments:
      bin: 'drupal chain:site:test-child --placeholder="project:foo" --placeholder="directory:some-dir" --placeholder="version:10"'
