# chain-npm.yml
commands:
  - command: exec
    arguments:
      bin: 'cd /vagrant/repos/%{{name}}/web; find . -type d \( -name node_modules -o -name contrib -o -path ./core \) -prune -o -name package.json -execdir sh -c "npm install" \;'
