commands:
# Build from template
  - command: exec
    arguments:
      bin: 'echo "This is a test %{{project|dennisdigital/drupal-project:8.x-dev}} %{{directory|/vagrant/repos/new-site}} %{{version|8.x-dev}}"'
